import { Plus, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import { addDevice, getDevices } from '../../services/device.service'
import { useDevices } from '../../hooks/useDevices'

export default function AddDeviceForm({ onClose }) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [formData, setFormData] = useState({
    name: '',
    deviceType: 'END',
    location: '',
    tag: '',
    description: '',
    subDevices: [],
  })
  const { setDevices } = useDevices()

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData((prev) => {
      const next = { ...prev, [name]: value }

      if (name === 'deviceType') {
        if (value !== 'DCB') {
          next.subDevices = []
        }
      }

      return next
    })
  }

  const addSubDevice = () => {
    setFormData((prev) => ({
      ...prev,
      subDevices: [...prev.subDevices, { name: '', type: '' }],
    }))
  }

  const removeSubDevice = (index) => {
    setFormData((prev) => ({
      ...prev,
      subDevices: prev.subDevices.filter((_, i) => i !== index),
    }))
  }

  const updateSubDevice = (index, field, value) => {
    setFormData((prev) => ({
      ...prev,
      subDevices: prev.subDevices.map((item, i) =>
        i === index ? { ...item, [field]: value } : item
      ),
    }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()

    if (!formData.name.trim()) {
      setError('Device name is required')
      return
    }

    if (!['END', 'DCB'].includes(formData.deviceType)) {
      setError('Please select a valid device type')
      return
    }

    const normalizedSubDevices = formData.subDevices
      .map((item) => ({ name: item.name.trim(), type: item.type.trim() }))
      .filter((item) => item.name && item.type)

    if (formData.deviceType === 'DCB' && normalizedSubDevices.length === 0) {
      setError('DCB devices require at least one sub-device')
      return
    }

    setLoading(true)
    setError(null)

    try {
      const payload = {
        name: formData.name.trim(),
        deviceType: formData.deviceType,
        location: formData.location.trim(),
        tag: formData.tag.trim(),
        description: formData.description.trim(),
        subDevices: formData.deviceType === 'DCB' ? normalizedSubDevices : [],
      }

      console.log('[AddDeviceForm] submitting payload:', payload)
      await addDevice(payload)

      // Refetch all devices to update the list
      const updatedDevices = await getDevices()
      setDevices(updatedDevices)

      // Close the form
      onClose()
    } catch (err) {
      console.error('[AddDeviceForm] create failed:', err)
      setError(err.message || 'Failed to create device')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="relative w-full max-w-2xl rounded-xl border border-border bg-surface p-6">
        <button
          onClick={onClose}
          disabled={loading}
          className="absolute right-4 top-4 text-textSecondary hover:text-textPrimary disabled:opacity-50"
        >
          <X className="h-5 w-5" />
        </button>

        <h2 className="mb-2 text-lg font-semibold text-textPrimary">Register Device</h2>
        <p className="text-xs text-textSecondary mb-6">Create END/DCB device. Device ID and MQTT credentials are generated by backend.</p>

        <form onSubmit={handleSubmit} className="space-y-6">
          {error && (
            <div className="rounded-lg bg-danger/10 border border-danger px-4 py-3">
              <p className="text-sm text-danger">{error}</p>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-textPrimary mb-2">
              Device Name *
            </label>
            <input
              type="text"
              name="name"
              placeholder="Energy Meter Block A"
              value={formData.name}
              onChange={handleChange}
              disabled={loading}
              required
              className="w-full rounded-lg border border-border bg-bg px-4 py-2 text-textPrimary placeholder:text-textSecondary focus:border-primary focus:outline-none disabled:opacity-50"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-textPrimary mb-2">Device Type *</label>
            <select
              name="deviceType"
              value={formData.deviceType}
              onChange={handleChange}
              disabled={loading}
              className="w-full rounded-lg border border-border bg-bg px-4 py-2 text-textPrimary focus:border-primary focus:outline-none disabled:opacity-50"
            >
              <option value="END">END</option>
              <option value="DCB">DCB</option>
            </select>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <label className="block text-sm font-medium text-textPrimary mb-2">Location</label>
              <input
                type="text"
                name="location"
                placeholder="Plant 1 - Block A"
                value={formData.location}
                onChange={handleChange}
                disabled={loading}
                className="w-full rounded-lg border border-border bg-bg px-4 py-2 text-textPrimary placeholder:text-textSecondary focus:border-primary focus:outline-none disabled:opacity-50"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-textPrimary mb-2">Description</label>
              <input
                type="text"
                name="description"
                placeholder="Main panel monitor"
                value={formData.description}
                onChange={handleChange}
                disabled={loading}
                className="w-full rounded-lg border border-border bg-bg px-4 py-2 text-textPrimary placeholder:text-textSecondary focus:border-primary focus:outline-none disabled:opacity-50"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-textPrimary mb-2">Tag (Panel/Label)</label>
              <input
                type="text"
                name="tag"
                placeholder="Panel-A"
                value={formData.tag}
                onChange={handleChange}
                disabled={loading}
                className="w-full rounded-lg border border-border bg-bg px-4 py-2 text-textPrimary placeholder:text-textSecondary focus:border-primary focus:outline-none disabled:opacity-50"
              />
            </div>
          </div>

          {formData.deviceType === 'DCB' && (
            <div className="space-y-4 rounded-lg border border-border p-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-textPrimary">DCB Sub-Devices</h3>
                <button
                  type="button"
                  onClick={addSubDevice}
                  disabled={loading}
                  className="inline-flex items-center gap-2 rounded-md bg-primary/15 px-3 py-1.5 text-xs font-medium text-primary hover:bg-primary/25 disabled:opacity-50"
                >
                  <Plus className="h-3.5 w-3.5" />
                  Add Sub-Device
                </button>
              </div>

              {formData.subDevices.length === 0 && (
                <p className="text-xs text-textSecondary">Add at least one sub-device for DCB registration.</p>
              )}

              {formData.subDevices.map((subDevice, index) => (
                <div key={index} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]">
                  <input
                    type="text"
                    placeholder="Sub-device name"
                    value={subDevice.name}
                    disabled={loading}
                    onChange={(e) => updateSubDevice(index, 'name', e.target.value)}
                    className="w-full rounded-lg border border-border bg-bg px-3 py-2 text-sm text-textPrimary placeholder:text-textSecondary focus:border-primary focus:outline-none disabled:opacity-50"
                  />
                  <input
                    type="text"
                    placeholder="Sub-device type"
                    value={subDevice.type}
                    disabled={loading}
                    onChange={(e) => updateSubDevice(index, 'type', e.target.value)}
                    className="w-full rounded-lg border border-border bg-bg px-3 py-2 text-sm text-textPrimary placeholder:text-textSecondary focus:border-primary focus:outline-none disabled:opacity-50"
                  />
                  <button
                    type="button"
                    onClick={() => removeSubDevice(index)}
                    disabled={loading}
                    className="rounded-lg border border-danger/40 px-3 py-2 text-danger hover:bg-danger/10 disabled:opacity-50"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              ))}
            </div>
          )}

          <p className="text-xs text-textSecondary">
            MQTT credentials and topic are generated automatically.
          </p>

          <div className="flex gap-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              disabled={loading}
              className="flex-1 rounded-lg border border-border px-4 py-2 text-sm font-medium text-textPrimary hover:bg-border/20 disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary/90 disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {loading ? '⏳ Creating...' : '➕ Add Device'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
